apiVersion: apps/v1
kind: Deployment
metadata:
  name: memoryleak-app-deployment
  labels:
    app: memoryleak-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memoryleak-app
  template:
    metadata:
      labels:
        app: memoryleak-app
    spec:
      containers:
      - name: memoryleak-app
        image: sumanth17121988/memoryleak-app:latest
        ports:
        - containerPort: 8082
        env:
        - name: JAVA_OPTS
          value: "-XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/heap-dumps/heapdump.hprof"
        volumeMounts:
        - name: heap-dump-volume
          mountPath: /heap-dumps
      volumes:
      - name: heap-dump-volume
        persistentVolumeClaim:
          claimName: heap-dump-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: heap-dump-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/dhrangdhariaritesh/heap-dumps
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heap-dump-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: memoryleak-app-service
  labels:
    app: memoryleak-app
spec:
  type: LoadBalancer
  selector:
    app: memoryleak-app
  ports:
  - protocol: TCP
    port: 8082    # External port to expose
    targetPort: 8082 # Port inside the container
